In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import tree 

import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
%matplotlib inline 

from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [4]:
tr = tree.DecisionTreeClassifier()
tr.fit(x_train,y_train)
tr.score(x_test,y_test)

0.8666666666666667

In [5]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [6]:
svm = SVC(kernel='rbf')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

1.0

In [7]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test,y_test)

1.0

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# **Use KFold for our digits example**

In [10]:
def get_score(model, x_train,x_test,y_train,y_test):
    model.fit(x_train, y_train)
    return model.score(x_test,y_test)

In [22]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)
scores_DT = []
scores_rf = []
scores_logst = []
scores_svm  = [] 
for train_index, test_index in folds.split(iris.data, iris.target):
     x_train, x_test, y_train, y_test = iris.data[train_index], iris.data[test_index], \
                                       iris.target[train_index], iris.target[test_index] 
     
     scores_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
#     scores_DT.append(get_score(tree(,  x_train, x_test, y_train, y_test))
     scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))
     scores_logst.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))  
    
        


In [23]:
scores_rf

[0.98, 0.94, 0.96]

In [24]:
scores_DT

[]

In [25]:
scores_logst

[0.96, 0.96, 0.94]

In [26]:
scores_svm

[0.98, 0.98, 0.96]

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [30]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.94])

In [31]:
cross_val_score(SVC(gamma='auto'), iris.data, iris.target, cv=3)

array([0.98, 0.98, 0.96])